# Site settings
title: MEAN.JS
email: your-email@domain.com
description: > # Full-Stack JavaScript Using MongoDB, Express, AngularJS, and Node.js
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://meanjs.org/" # the base hostname & protocol for your site
twitter_username: Meanjsorg
github_username:  meanjs

# Build settings
markdown: kramdown
